#!/bin/bash

cd "$(dirname "$0")" # http://stackoverflow.com/questions/3349105/how-to-set-current-working-directory-to-the-directory-of-the-script

export LC_CTYPE=C LANG=C

find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Abdul Latif Jameel Poverty Action Lab/Poverty Action Lab/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Republic of Turkey/Turkey/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ARC Centre of Excellence in Population Ageing Research/ARC Centre/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Graduate School of Business Administration/Business/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of London, University College London (United Kingdom)/UCL/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Shanghai University of Finance and Economics/SHUFE/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of London, University College London/UCL/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of London, University College London/UCL/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/London School of Economics and Political Science (United Kingdom)/LSE/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The University/University/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Wisconsin, Madison/Wisconsin/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Wisconsin - Madison/Wisconsin/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, Santa Barbara/UCSB/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, Berkeley/Berkeley/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, San Diego/UCSD/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, Irvine/Cal-Irvine/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, Irvine/Cal-Merced/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The Ohio State University/Ohio State/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Ohio State University Fisher College of Business/Ohio State B-School/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Texas at Austin/UT-Austin/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The State University of New Jersey//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/- New Brunswick//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/State University of New York/SUNY/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, Los Angeles/UCLA/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Southern California/USC/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Universite de  Montreal/Montreal/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Georgia J. M. Tull School of Accounting/Georgia(Accounting)/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The University of North Carolina at Chapel Hill/UNC/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Maryland, College Park/UMD/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of North Carolina at Chapel Hill/UNC/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Nevada, Las Vegas/UNLV/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/UCLA Anderson School of Management/UCLA-Anderson/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Consumer Financial Protection Bureau/CFPB/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Haas Schoolof Business UC Berkeley/Berkeley-Haas/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Haas School of Business/Haas/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Boston University/BU/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/New York University/NYU/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FR Board of Governors/FRB/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Board of Governors/FRB/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Board of governors/FRB/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Chicago Booth/Booth/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Chicago Booth School of Business/Booth/g' 
#find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ College//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Boston College/BC/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB St. Louis/FRB-StL/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Washington University in St. Louis/WUSTL/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Arizona State University/ASU/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Upenn/Pennsylvania/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The Johns Hopkins University/JHU/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Johns Hopkins University/JHU/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Hong Kong University of Science and Technology/HKUST/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Hong Kong (Hong Kong)/University of Hong Kong/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Science and Technology/UST/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Science and Technology/ST/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB New York/FRB-NY/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRBNY/FRB-NY/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB Chicago/FRB-Chicago/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Yale School of Management/Yale SOM/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Microsoft Research/Microsoft/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Wisconsin, Madison/Wisconsin/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Colorado, Boulder/Colorado Boulder/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB St. Louis/FRB-StL/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB Richmond/FRB-Richmond/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Dept. of //g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Business School/Business/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Kellog School of Management/Kellog/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Northwestern, Kellog/Kellog/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/" ,/",/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/School of Business/Business/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/of Business/Business/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/School of Economics//g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ Economics//g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/FRB /FRB-/g'
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Massachusetts Institute of Technology/MIT/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Institute of Technology/Tech/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California, /Cal/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of California/Cal/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/International Food Policy Research/IFPRI/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/The University of Pennsylvania/Penn/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of Pennsylvania/Penn/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ University//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ (United Kingdom)//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ (Hong Kong)//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/University of //g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ Universita//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Universita//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/Pennsylvania/Penn/g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ The//g' 
find . -name '*.csv' -print0 | xargs -0 sed -i -e 's/ (Canada)//g' 
