#!/bin/bash

# Fix a bug prsent today (2017-02-23) using code from
# http://www.webupd8.org/2016/06/fix-dropbox-indicator-icon-and-menu-not.html

if [ "$USER" != "methods" ]; then
    echo "Dropbox should be installed when you are logged in with the username 'methods'"
    exit 1 # Signals a failure 
fi

dropbox_status=`dropbox status` # get the message obtained from running the shell command
dropbox_done=true
done_message="Up to date"
if [ "$dropbox_status" != "$done_message" ]; then
    dropbox_done=false ; echo -n 'Waiting for first Sync to complete .'
fi

while [ "$dropbox_done" == "false" ] ; do
#    echo -n . # add another dot to the end of the Waiting text
    sleep 1
    dropbox_status=`dropbox status`
    echo dropbox_status '=' "$dropbox_status"
    [ "$dropbox_status" == "$done_message" ] && dropbox_done=true
done

sleep 10

# Generate the command to autostart
dropbox autostart y

# Stop dropbox so we can modify it
dropbox stop

# ~/.config/autostart/dropbox.desktop is executed on startup -- maybe autogenerated by installation of the app
# if it exists, rename it to start_dropbox
if ! [ -e ~/.config/autostart/dropbox.desktop ]; then
    echo 'Something is wrong -- the "dropbox autostart y" command should have generated a file:"'
    echo ~/.config/autostart/dropbox.desktop
    echo ''
    echo 'But that file is not there.  Aborting.'
    exit 1
fi

cp ~/.config/autostart/dropbox.desktop ~/.config/autostart/start_dropbox.desktop
# Rename the line beginning Exec= to make the command be "dbus-launch dropbox start -i" 
sed -i 's/^Exec=.*/Exec=dbus-launch dropbox start -i/' ~/.config/autostart/start_dropbox.desktop
dropbox autostart n # Gets rid of the original of the dropbox.desktop file we just copied and changed 
sudo mkdir -p ~/.local/share/applications/ # This SHOULD already exist, if any desktop applications have been installed
# Copying the global command to the local directory 
cp /usr/share/applications/dropbox.desktop ~/.local/share/applications/
# Fix it
sed -i 's/^Exec=.*/Exec=dbus-launch dropbox start -i/' ~/.local/share/applications/dropbox.desktop
sleep 1

dbus-launch dropbox start

if [ ! -e /Methods ]; then
    echo 'Linking /Methods to /home/methods/Dropbox/Methods'
    sudo ln -fs /home/methods/Dropbox/Methods /
fi

echo ''
echo "Now the dropbox icon should be working; if not, launch by hand (using the mouse menu, upper left of the VirtualBox window)"
echo -n 'Hit return when icon is visible:'
read answer
echo ''
echo "(Changes just completed by " $0 " should make Dropbox autostart when methods user signs in, rather than at system boot)."
echo ''
echo "Click icon, go to Preferences, and under System untick 'Start Dropbox on System Startup'"
echo ''
echo -n 'Hit return when you have followed these instructions:'
read answer




